AllCops:
  TargetRubyVersion: 2.4.2
  DisplayCopNames: true
  Exclude:
    - 'test/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'

# Customize rules
Metrics/LineLength:
  Max: 100

MethodLength:
  Max: 30